
package ruleta;

import java.applet.AudioClip;
import java.awt.Image;
import java.util.Date;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 * Codigo practico, GUI y Ficheros.
 * Universidad Catolica Santiago de Guayaquil.
 * @author PC
 */
public class Ruleta extends javax.swing.JFrame {

    static int contador = 0;

    /**
     * Creates new form Ruleta
     */
    public Ruleta() {
        initComponents();

        jButton2.setIcon(setIcono("/imagenes botones/girar.png", jButton2));
        jButton2.setPressedIcon(setIconoPresionado("/imagenes botones/girar.png", jButton2, 5, 5));
        jButton3.setIcon(setIcono("/imagenes botones/salir.png", jButton3));
        jButton3.setPressedIcon(setIconoPresionado("/imagenes botones/salir.png", jButton3, 5, 5));
        jButton4.setIcon(setIcono("/imagenes botones/pausar.png", jButton4));
        jButton4.setPressedIcon(setIconoPresionado("/imagenes botones/pausar.png", jButton4, 5, 5));
    }

    public Icon setIcono(String url, JButton boton) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }

    public Icon setIconoPresionado(String url, JButton boton, int ancho, int altura) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int width = boton.getWidth() - ancho;
        int heigth = boton.getHeight() - altura;
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, heigth, Image.SCALE_DEFAULT));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(571, 400));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("<html><center>\n");
        jLabel4.setDoubleBuffered(true);
        jLabel4.setFocusCycleRoot(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 290, 430, 50);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Ruleta de la Fortuna");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 410, 56);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ruleta1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 170, 180);

        jButton2.setText("Girar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 80, 100, 90);

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 190, 100, 90);

        jButton4.setText("Stop");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(350, 80, 100, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void moverRuleta() {
        TimerTask tarea;
        contador = 0;
        int velocidad = 1;
        int velmil = (velocidad * 1000) / 20;

        tarea = new TimerTask() {

            public void run() {
                Icon icono;
                switch (contador) {
                    case 0:
                        contador = 1;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta2.png"));
                        ruleta.jLabel2.setIcon(icono);

                        break;
                    case 1:
                        contador = 2;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta3.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));

                        break;
                    case 2:
                        contador = 3;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta4.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 3:
                        contador = 4;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta5.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 4:
                        contador = 5;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta6.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 5:
                        contador = 6;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta7.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 6:
                        contador = 7;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta8.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 7:
                        contador = 8;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta9.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 8:
                        contador = 9;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta10.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 9:
                        contador = 10;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta11.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 10:
                        contador = 11;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta12.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 11:
                        contador = 12;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta13.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 12:
                        contador = 13;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta14.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 13:
                        contador = 14;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta15.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 14:
                        contador = 15;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta16.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 15:
                        contador = 16;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta17.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 16:
                        contador = 17;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta18.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 17:
                        contador = 18;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta19.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 18:
                        contador = 19;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta20.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 19:
                        contador = 20;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta21.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 20:
                        contador = 21;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta22.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 21:
                        contador = 22;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta23.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;

                    case 22:
                        contador = 23;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta24.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 23:
                        contador = 24;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta25.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 24:
                        contador = 25;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta26.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 25:
                        contador = 26;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta27.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 26:
                        contador = 27;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta28.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 27:
                        contador = 28;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta29.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 28:
                        contador = 29;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta30.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 29:
                        contador = 30;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta31.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 30:
                        contador = 31;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta32.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 31:
                        contador = 32;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta33.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 32:
                        contador = 33;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta34.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 33:
                        contador = 34;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta35.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 34:
                        contador = 35;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta36.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 35:
                        contador = 36;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta37.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 36:
                        contador = 37;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta38.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 37:
                        contador = 38;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta39.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 38:
                        contador = 39;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta40.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 39:
                        contador = 40;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta41.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 40:
                        contador = 41;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta42.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 41:
                        contador = 42;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta43.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 42:
                        contador = 43;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta44.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 43:
                        contador = 44;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta45.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 44:
                        contador = 45;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta46.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 45:
                        contador = 46;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta47.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 46:
                        contador = 47;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta48.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 47:
                        contador = 48;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta49.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 48:
                        contador = 49;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta50.png"));
                        ruleta.jLabel2.setIcon(icono);
//                         ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 49:
                        contador = 50;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta51.png"));
                        ruleta.jLabel2.setIcon(icono);
//                         ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 50:
                        contador = 51;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta52.png"));
                        ruleta.jLabel2.setIcon(icono);
//                         ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 51:
                        contador = 52;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta53.png"));
                        ruleta.jLabel2.setIcon(icono);
//                         ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 52:
                        contador = 53;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta54.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 53:
                        contador = 54;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta55.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 54:
                        contador = 55;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta56.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 55:
                        contador = 56;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta57.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;
                    case 56:
                        contador = 0;
                        icono = new ImageIcon(getClass().getResource("/imagenes/ruleta1.png"));
                        ruleta.jLabel2.setIcon(icono);
//                        ruleta.jLabel4.setText(String.valueOf(lc.recuperar().getSiguiente().getDato()));
                        break;

                }

            }

        };

        t1 = new Timer();
        t1.scheduleAtFixedRate(tarea, velmil, velmil);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        moverRuleta();
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/sonido/girar.wav"));
        sound.play();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        System.exit(0);

    }//GEN-LAST:event_jButton3ActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        t1.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                Icon icono;
                icono = new ImageIcon(getClass().getResource("/imagenes/ruleta2.png"));
                ruleta.jLabel2.setIcon(icono);
                ruleta.jLabel4.setText(lc.recuperar().getDato().toString());
                //To change body of generated methods, choose Tools | Templates.
            }
        }, 5, 5);
        t1.cancel();
        Random randomStop = new Random();

        int contadorStop = randomStop.nextInt(8);
        switch (contadorStop) {
            case 0:
                ruleta.jLabel4.setText(lc.recuperar().getSiguiente().getDato().toString());
                break;
            case 1:
                ruleta.jLabel4.setText(lc.recuperar().getSiguiente().getSiguiente().getDato().toString());
                break;
            case 2:
                ruleta.jLabel4.setText(lc.recuperar().getSiguiente().getSiguiente().getSiguiente().getDato().toString());
                break;
            case 3:
                ruleta.jLabel4.setText(lc.recuperar().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getDato().toString());

                break;
            case 4:
                ruleta.jLabel4.setText(lc.recuperar().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getDato().toString());

                break;
            case 5:
                ruleta.jLabel4.setText(lc.recuperar().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getDato().toString());

                break;
            case 6:
                ruleta.jLabel4.setText(lc.recuperar().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getDato().toString());

                break;
            case 7:
                ruleta.jLabel4.setText(lc.recuperar().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getSiguiente().getDato().toString());

                break;
            case 8:
                ruleta.jLabel4.setText(lc.recuperar().getDato().toString());
                break;
        }
        AudioClip sound;
        sound = java.applet.Applet.newAudioClip(getClass().getResource("/sonido/parar.wav"));
        sound.play();


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked


    }//GEN-LAST:event_jButton2MouseClicked
    public static Timer t1 = null;
    /**
     * @param args the command line arguments
     */
    public static Ruleta ruleta = new Ruleta();
    static ListaCircular lc = new ListaCircular();
    static Persona p1 = new Persona("01", "Daniela", new Date());
    static Persona p2 = new Persona("02", "Mark", new Date());
    static Persona p3 = new Persona("03", "Chris", new Date());
    static Persona p4 = new Persona("04", "Thomas", new Date());
    static Persona p5 = new Persona("05", "Salim", new Date());
    static Persona p6 = new Persona("06", "Goku", new Date());
    static Persona p7 = new Persona("07", "Marcos", new Date());
    static Persona p8 = new Persona("08", "Robert", new Date());
    
    
    

    public static void main(String args[]) {

        lc.insertarAlInicio(p1);
        lc.insertarAlInicio(p2);
        lc.insertarAlInicio(p2);
        lc.insertarAlInicio(p3);
        lc.insertarAlInicio(p4);
        lc.insertarAlInicio(p5);
        lc.insertarAlInicio(p6);
        lc.insertarAlInicio(p7);
        lc.insertarAlInicio(p8);
        lc.listar();
        TimerTask tarea;

        int velocidad = 1;
        int velmil = (velocidad * 1100) / 20;

        ruleta.setVisible(true);
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
